context: {}
package:

  name: ecrad_pylib
  version: 1.0.22

source:
  git_rev: 1.0.22
  git_url: https://github.com/AreWeDreaming/ECRad_PyLib

build:
    number: 1

requirements:
  build:
    - conda-forge::python
    - conda-forge::numpy <=1.26
    - conda-forge::pip >=21.0
    - conda-forge::setuptools >=57.4
    - conda-forge::build >=0.7
  run:
    - conda-forge::python
    - conda-forge::numpy <=1.26
    - conda-forge::scipy >=1.7.3
    - conda-forge::matplotlib
    - conda-forge::hdf5
    - conda-forge::netcdf4 >=1.5.6
    - conda-forge::h5py
    - conda-forge::wxpython
    - conda-forge::f90nml >=1.3.1
    - arewedreaming::plasma_math_tools
    - arewedreaming::ecrad_core
    - conda-forge::psutil
    - conda-forge::cython
    - conda-forge::omas

